swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Jon REST API Test
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /post:
    get:
      operationId: "post.read"
      tags:
        - "Post"
      summary: "The post data structure supported by the server application"
      description: "Read the list of post"
      responses:
        200:
          description: "Successful read post list operation"
          schema:
            type: "array"
            items:
              properties:
                title:
                  type: "string"
                body:
                  type: "string"
                link: 
                  type: "boolean"
                url:
                  type: "string"
                timestamp:
                  type: "string"
                user_id:
                  type: integer
                category_id:
                  type: integer
                vote_count:
                  type: integer
